In [7]:
import pandas as pd
import numpy as np

df=pd.read_csv('lab_1_data.csv')
df

Unnamed: 0   x1   x2       u         e         y
0            0 -1.0 -1.0 -2.5700  0.184213 -2.385787
1            1 -1.0 -0.5 -1.0200  0.224978 -0.795022
2            2 -1.0  0.0 -0.4700  0.476234  0.006234
3            3 -1.0  0.5 -0.9200  0.066598 -0.853402
4            4 -1.0  1.0 -2.3700 -0.198972 -2.568972
5            5 -0.5 -1.0 -1.3425 -0.052922 -1.395422
6            6 -0.5 -0.5  0.2075  0.370028  0.577528
7            7 -0.5  0.0  0.7575  0.133969  0.891469
8            8 -0.5  0.5  0.3075  0.349004  0.656504
9            9 -0.5  1.0 -1.1425 -0.762287 -1.904787
10          10  0.5 -1.0  1.1575  0.093277  1.250777
11          11  0.5 -0.5  2.7075 -0.048116  2.659384
12          12  0.5  0.0  3.2575 -0.460753  2.796747
13          13  0.5  0.5  2.8075 -0.216694  2.590806
14          14  0.5  1.0  1.3575 -0.288687  1.068813
15          15  1.0 -1.0  2.4300  0.353569  2.783569
16          16  1.0 -0.5  3.9800  0.944602  4.924602
17          17  1.0  0.0  4.5300  0.460651  4.990651
18          18  1.0  0.5  4.0800  0.221977  4.301977
19          19  1.0  1.0  2.6300  0.159310  2.789310

In [8]:
#предлагаю если что оставшийся импорт библиотек сделать здесь
import scipy.stats

In [9]:
#наша новая функция(с доп регрессором)
def u_func(x1, x2):
    return 2 + 2.5*x1 + 0.03*x1*x1 + 0.1*x2 - 2*x2*x2+0.001*x2**3

In [10]:
#наши старые х1 и х2
x1 = np.array([-1, -0.5, 0.5, 1])
x2 = np.array([-1, -0.5, 0, 0.5, 1])
u = np.array([])

for i in x1:
    for j in x2:
        u = np.append(u, u_func(i, j))

In [11]:
#изменила генерацию e, теперь в функцию подается среднеквадратичное отклонение
n = len(u)
p = 0.1 # доля
u_average = np.full(n, np.mean(u))

# считаем ошибку наблюдения
w_sq = np.dot((u - u_average).transpose(), (u - u_average)) / (n - 1)
d = (p * w_sq)**(1/2)
e = np.random.normal(0, d, n)

In [12]:
# дополнительные столбцы в датафрейме
df['x1^2'] = df['x1']**2
df['x2^2'] = df['x2']**2
df['x2^3'] = df['x2']**3
df

Unnamed: 0   x1   x2       u         e         y  x1^2  x2^2   x2^3
0            0 -1.0 -1.0 -2.5700  0.184213 -2.385787  1.00  1.00 -1.000
1            1 -1.0 -0.5 -1.0200  0.224978 -0.795022  1.00  0.25 -0.125
2            2 -1.0  0.0 -0.4700  0.476234  0.006234  1.00  0.00  0.000
3            3 -1.0  0.5 -0.9200  0.066598 -0.853402  1.00  0.25  0.125
4            4 -1.0  1.0 -2.3700 -0.198972 -2.568972  1.00  1.00  1.000
5            5 -0.5 -1.0 -1.3425 -0.052922 -1.395422  0.25  1.00 -1.000
6            6 -0.5 -0.5  0.2075  0.370028  0.577528  0.25  0.25 -0.125
7            7 -0.5  0.0  0.7575  0.133969  0.891469  0.25  0.00  0.000
8            8 -0.5  0.5  0.3075  0.349004  0.656504  0.25  0.25  0.125
9            9 -0.5  1.0 -1.1425 -0.762287 -1.904787  0.25  1.00  1.000
10          10  0.5 -1.0  1.1575  0.093277  1.250777  0.25  1.00 -1.000
11          11  0.5 -0.5  2.7075 -0.048116  2.659384  0.25  0.25 -0.125
12          12  0.5  0.0  3.2575 -0.460753  2.796747  0.25  0.00  0.000
13          13  0.5  0.5  2.8075 -0.216694  2.590806  0.25  0.25  0.125
14          14  0.5  1.0  1.3575 -0.288687  1.068813  0.25  1.00  1.000
15          15  1.0 -1.0  2.4300  0.353569  2.783569  1.00  1.00 -1.000
16          16  1.0 -0.5  3.9800  0.944602  4.924602  1.00  0.25 -0.125
17          17  1.0  0.0  4.5300  0.460651  4.990651  1.00  0.00  0.000
18          18  1.0  0.5  4.0800  0.221977  4.301977  1.00  0.25  0.125
19          19  1.0  1.0  2.6300  0.159310  2.789310  1.00  1.00  1.000

In [13]:
class MyLinearRegression:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self.k = None
        self.for_sigma = None
        
        
    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)

        X = np.hstack((np.ones((X.shape[0], 1)), X))

        self.k = np.linalg.inv(X.T @ X) @ X.T @ y
        self.for_sigma = np.linalg.inv(X.T @ X)

        self.coef_ = self.k[::][1:]
        self.intercept_ = self.k[::][0]
        
    def predict(self, X):
        X = np.hstack((np.ones((X.shape[0], 1)), X))
        y_pred = X @ self.k        
        return y_pred
    
    def get_param(self):
        return self.coef_, self.intercept_

In [14]:
LinModel = MyLinearRegression()

In [15]:
#добавила в х новый регрессор
x = df[['x1','x1^2','x2', 'x2^2','x2^3']]
y = df['y']

In [16]:
LinModel.fit(x,y)
y_predict = LinModel.predict(x)

In [17]:
LinModel.get_param()

(array([ 2.57261407,  0.53351184, -0.1873366 , -2.29696999,  0.07873997]),
 1.934289016591541)

In [18]:
tetta_wave_j = LinModel.get_param()[1] 
tetta = LinModel.get_param()[0] 
tetta = np.append(tetta_wave_j, tetta) 
print(tetta)

[ 1.93428902  2.57261407  0.53351184 -0.1873366  -2.29696999  0.07873997]


### Для вычисления сигмочек и тд

In [19]:

sigma = np.sqrt(p*w_sq)
e_predict = y - y_predict
sigma_sq_predict = e_predict.T @ e_predict / (n - 6)
print(sigma_sq_predict)
F = sigma_sq_predict/sigma**2
FT = scipy.stats.f.ppf(q=1-0.05, dfn=9999, dfd=16)
print('F =', F)
print('FT =', FT)
print('F < FT:', F < FT)

0.07804841451360676
F = 0.16078630657779167
FT = 2.0102414060038662
F < FT: True


## Второй пункт. Доверительные интервалы

In [20]:
true_tetta = [2,2.5,0.03,0.1,-2,0.001]
for j in range(0,6):
    sigma_tetta_wave_j = (LinModel.for_sigma[j][j]*sigma_sq_predict)**(1/2)
    print(f'Минимальное значение:{tetta[j]-FT*sigma_tetta_wave_j}<={true_tetta[j]}<= Макс.знач{tetta[j]+FT*sigma_tetta_wave_j}')

Минимальное значение:1.6477512272081825<=2<= Макс.знач2.2208268059748995
Минимальное значение:2.413768449325557<=2.5<= Макс.знач2.73145969378804
Минимальное значение:0.19863586744342737<=0.03<= Макс.знач0.868387817573296
Минимальное значение:-0.7209425813343395<=0.1<= Макс.знач0.3462693758466051
Минимальное значение:-2.5971599993061782<=-2<= Макс.знач-1.9967799803416375
Минимальное значение:-0.513242712001087<=0.001<= Макс.знач0.6707226521232748


## Третий пункт. Гипотеза о незначимости параметра

In [21]:
#значение F критического, с которым будем сравнивать
F_crit=scipy.stats.f.isf(0.05,1,n-6)
print(F_crit)

4.600109936669421


In [22]:
for j in range(0,6):
    djj=LinModel.for_sigma[j][j]*sigma_sq_predict
    F = (tetta[j]**2)/djj
    print(f" Номер: {j},Значение F={F}, F<fcrit  {F<F_crit}")

 Номер: 0,Значение F=184.15153691779807, F<fcrit  False
 Номер: 1,Значение F=1059.973992171587, F<fcrit  False
 Номер: 2,Значение F=10.256910689804114, F<fcrit  False
 Номер: 3,Значение F=0.498081412698534, F<fcrit  True
 Номер: 4,Значение F=236.59992434966622, F<fcrit  False
 Номер: 5,Значение F=0.07149388788323119, F<fcrit  True


## Четвертый пункт. Проверка гипотезы о незначимости самой регрессии

In [23]:
# theta - массив найденных параметров
theta_intercept = LinModel.get_param()[1]
theta = LinModel.get_param()[0]
theta = np.append(theta_intercept, theta)
theta

array([ 1.93428902,  2.57261407,  0.53351184, -0.1873366 , -2.29696999,
        0.07873997])

In [24]:
# Формулы:
# F = (RSSh - RSS) * (n - m) / q / RSS
# RSSh = sum( ( yi - y_aver )^2 )
# RSS = (y - X*theta)T * (y - X*theta)

m = theta.size
q = m - 1
X_wout_intercept = np.array(x)
X_arr = np.hstack((np.ones((X_wout_intercept.shape[0], 1)), X_wout_intercept))

rssh = 0
rss = np.dot((y - np.dot(X_arr, theta)).T, (y - np.dot(X_arr, theta)))

# y_aver - среднее истинного y
y_aver = np.average(y)
for i in range(n):
  rssh += pow((y[i] - y_aver), 2)

F_regr_level = ((rssh - rss) / q) / (rss / (n - 6))
FT_regr_level = scipy.stats.f.ppf(q=1-0.05, dfn=q, dfd=n-m)

print('Незначимость регресии: ')
print('F = ', F_regr_level)
print('FT = ', FT_regr_level)
print('F < FT', F_regr_level < FT_regr_level)

Незначимость регресии: 
F =  261.75197713307824
FT =  2.958248913122196
F < FT False


## Пятый и шестой пункты. Доверительное оценивание для мат. ожидания
#### для истинного значения математического ожидания функции отклика в точке фиксированной

In [25]:
nuMin = []
nuOrig = []
nuMax = []

In [26]:
# фиксируем x1 = -1
X1 = x1[0]
X2 = x2[0]

# оригинальная тетта
theta_original = np.array([2, 2.5, 0.03, 0.1, -2, 0.001])

# Считаем корень из F(alpha, 1, fR)
F_di = pow(scipy.stats.f.ppf(q=1-0.05, dfn=1, dfd=n-m), 0.5)

i = 0
while (X2 <= x2[4]):
    func = np.array([1, X1, X1**2, X2, X2**2, X1**3])
    # считаем сигму
    sigma_new = pow(sigma_sq_predict, 0.5) * pow(np.dot(np.dot(func.T, np.linalg.inv(np.dot(X_arr.T, X_arr)) ), func), 0.5) 
    
    # считаем этту
    nu = np.dot(func.T, theta)

    # считаем границы
    nu_min = nu - F_di * sigma_new
    nu_max = nu + F_di * sigma_new
    # что есть этта оригинал?
    nu_original = np.dot(func.T, theta_original)
    X2 = X2 + 0.2

    # чтобы удобней переносить в эксель было
    print(f'{nu_min},{nu_original},{nu_max}')
    #Для графиков
    nuMin.append(nu_min)
    nuOrig.append(nu_original)
    nuMax.append(nu_max)
    i += 1

-2.6608136014091857,-2.5709999999999997,-1.9255595377868753
-1.8649426883721376,-1.8310000000000002,-1.1425466992482565
-1.3168000763865475,-1.2510000000000001,-0.47932075803000534
-0.9820977363092145,-0.8310000000000001,0.029830256724678206
-0.8401160269006622,-0.5710000000000001,0.3641867037763171
-0.8829775000883902,-0.471,0.515871135052411
-1.109049006170264,-0.5309999999999999,0.4832504008508254
-1.5196112879592265,-0.751,0.2676052439845028
-2.1174231135412525,-1.1309999999999998,-0.12830556746058108
-2.9059968979161264,-1.671,-0.700969618484643
-3.889125533478624,-2.371,-1.4465940166929057


### Доверительное оценивание для мат. ожидания
#### для истинного значения математического ожидания самого отклика

In [27]:
yMin = []
yOrig = []
yMax = []

In [28]:
# фиксируем х = -1
X1 = x1[0]
X2 = x2[0]

# Считаем корень из F(alpha, 1, fR)
F_di = pow(scipy.stats.f.ppf(q=1-0.05, dfn=1, dfd=n-m), 0.5)

while (X2 <= x2[4]):
    func = np.array([1, X1, X1**2, X2, X2**2, X1**3])

    # считаем сигму
    sigma_new = pow(sigma_sq_predict * (1 + np.dot(np.dot(func.T, np.linalg.inv(np.dot(X_arr.T, X_arr))), func)), 0.5)

    y_pr = np.dot(func.T, theta)
    y_min = y_pr - sigma_new * F_di
    y_max = y_pr + sigma_new * F_di
    # вот тут вопрос: что есть у оригинал
    y_original = np.dot(func.T, theta_original)
    X2 = X2 + 0.2
    
    #Для графиков
    print(f'{y_min},{y_original},{y_max}')
    yMin.append(y_min)
    yOrig.append(y_original)
    yMax.append(y_max)
    i += 1

-2.9961665989470982,-2.5709999999999997,-1.5902065402489627
-2.203384085512025,-1.8310000000000002,-0.8041053021083691
-1.6290694385712627,-1.2510000000000001,-0.16705139584529005
-1.26037276771471,-0.8310000000000001,0.3081052881301738
-1.0874454170383303,-0.5710000000000001,0.6115160939139851
-1.104544856288256,-0.471,0.7374384912522769
-1.309335772057174,-0.5309999999999999,0.6835371667377353
-1.701905908013131,-0.751,0.4498998640384073
-2.283975205223504,-1.1309999999999998,0.03824652422167052
-3.058301019034438,-1.671,-0.5486654973663312
-4.028198460769673,-2.371,-1.307521089401857


In [ ]:
x = np.arange(-1,1,0.2)