In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('lab_1_data.csv')
df

Unnamed: 0   x1   x2       u         e         y
0            0 -1.0 -1.0 -2.5700  0.673689 -1.896311
1            1 -1.0 -0.5 -1.0200 -0.409092 -1.429092
2            2 -1.0  0.0 -0.4700 -0.183428 -0.653428
3            3 -1.0  0.5 -0.9200 -1.135839 -2.055839
4            4 -1.0  1.0 -2.3700  0.101378 -2.268622
5            5 -0.5 -1.0 -1.3425  0.507489 -0.835011
6            6 -0.5 -0.5  0.2075  0.621255  0.828755
7            7 -0.5  0.0  0.7575  0.802619  1.560119
8            8 -0.5  0.5  0.3075  0.100901  0.408401
9            9 -0.5  1.0 -1.1425  0.387085 -0.755415
10          10  0.5 -1.0  1.1575  0.297546  1.455046
11          11  0.5 -0.5  2.7075 -0.867049  1.840451
12          12  0.5  0.0  3.2575  0.126244  3.383744
13          13  0.5  0.5  2.8075 -0.918606  1.888894
14          14  0.5  1.0  1.3575  0.188098  1.545598
15          15  1.0 -1.0  2.4300 -0.132728  2.297272
16          16  1.0 -0.5  3.9800  0.203584  4.183584
17          17  1.0  0.0  4.5300 -0.553143  3.976857
18          18  1.0  0.5  4.0800 -0.033915  4.046085
19          19  1.0  1.0  2.6300 -0.025597  2.604403

In [2]:
#предлагаю если что оставшийся импорт библиотек сделать здесь
import scipy.stats

In [3]:
#наша новая функция(с доп регрессором)
def u_func(x1, x2):
    return 2 + 2.5*x1 + 0.03*x1*x1 + 0.1*x2 - 2*x2*x2+0.001*x2**3

In [4]:
#наши старые х1 и х2
x1 = np.array([-1, -0.5, 0.5, 1])
x2 = np.array([-1, -0.5, 0, 0.5, 1])
u = np.array([])

for i in x1:
    for j in x2:
        u = np.append(u, u_func(i, j))

In [5]:
#изменила генерацию e, теперь в функцию подается среднеквадратичное отклонение
n = len(u)
p = 0.1 # доля
u_average = np.full(n, np.mean(u))

# считаем ошибку наблюдения
w_sq = np.dot((u - u_average).transpose(), (u - u_average)) / (n - 1)
d = (p * w_sq)**(1/2)
e = np.random.normal(0, d, n)

In [6]:
# дополнительные столбцы в датафрейме
df['x1^2'] = df['x1']**2
df['x2^2'] = df['x2']**2
df['x2^3'] = df['x2']**3
df

Unnamed: 0   x1   x2       u         e         y  x1^2  x2^2   x2^3
0            0 -1.0 -1.0 -2.5700  0.673689 -1.896311  1.00  1.00 -1.000
1            1 -1.0 -0.5 -1.0200 -0.409092 -1.429092  1.00  0.25 -0.125
2            2 -1.0  0.0 -0.4700 -0.183428 -0.653428  1.00  0.00  0.000
3            3 -1.0  0.5 -0.9200 -1.135839 -2.055839  1.00  0.25  0.125
4            4 -1.0  1.0 -2.3700  0.101378 -2.268622  1.00  1.00  1.000
5            5 -0.5 -1.0 -1.3425  0.507489 -0.835011  0.25  1.00 -1.000
6            6 -0.5 -0.5  0.2075  0.621255  0.828755  0.25  0.25 -0.125
7            7 -0.5  0.0  0.7575  0.802619  1.560119  0.25  0.00  0.000
8            8 -0.5  0.5  0.3075  0.100901  0.408401  0.25  0.25  0.125
9            9 -0.5  1.0 -1.1425  0.387085 -0.755415  0.25  1.00  1.000
10          10  0.5 -1.0  1.1575  0.297546  1.455046  0.25  1.00 -1.000
11          11  0.5 -0.5  2.7075 -0.867049  1.840451  0.25  0.25 -0.125
12          12  0.5  0.0  3.2575  0.126244  3.383744  0.25  0.00  0.000
13          13  0.5  0.5  2.8075 -0.918606  1.888894  0.25  0.25  0.125
14          14  0.5  1.0  1.3575  0.188098  1.545598  0.25  1.00  1.000
15          15  1.0 -1.0  2.4300 -0.132728  2.297272  1.00  1.00 -1.000
16          16  1.0 -0.5  3.9800  0.203584  4.183584  1.00  0.25 -0.125
17          17  1.0  0.0  4.5300 -0.553143  3.976857  1.00  0.00  0.000
18          18  1.0  0.5  4.0800 -0.033915  4.046085  1.00  0.25  0.125
19          19  1.0  1.0  2.6300 -0.025597  2.604403  1.00  1.00  1.000

In [7]:
class MyLinearRegression:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self.k = None
        self.for_sigma = None
        
        
    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)

        X = np.hstack((np.ones((X.shape[0], 1)), X))

        self.k = np.linalg.inv(X.T @ X) @ X.T @ y
        self.for_sigma = np.linalg.inv(X.T @ X)

        self.coef_ = self.k[::][1:]
        self.intercept_ = self.k[::][0]
        
    def predict(self, X):
        X = np.hstack((np.ones((X.shape[0], 1)), X))
        y_pred = X @ self.k        
        return y_pred
    
    def get_param(self):
        return self.coef_, self.intercept_

In [8]:
LinModel = MyLinearRegression()

In [9]:
#добавила в х новый регрессор
x = df[['x1','x1^2','x2', 'x2^2','x2^3']]
y = df['y']

In [10]:
LinModel.fit(x,y)
y_predict = LinModel.predict(x)

In [11]:
LinModel.get_param()

(array([ 2.38919478, -0.33542298, -0.38309225, -1.56799314,  0.39621324]),
 np.float64(1.999910544146073))

In [12]:
tetta_wave_j = LinModel.get_param()[1] 
tetta = LinModel.get_param()[0] 
tetta = np.append(tetta_wave_j, tetta) 
print(tetta)

[ 1.99991054  2.38919478 -0.33542298 -0.38309225 -1.56799314  0.39621324]


### Для вычисления сигмочек и тд

In [13]:

sigma = np.sqrt(p*w_sq)
e_predict = y - y_predict
sigma_sq_predict = e_predict.T @ e_predict / (n - 6)
print(sigma_sq_predict)
F = sigma_sq_predict/sigma**2
FT = scipy.stats.f.ppf(q=1-0.05, dfn=9999, dfd=16)
print('F =', F)
print('FT =', FT)
print('F < FT:', F < FT)

0.283183803079825
F = 0.5833824820607955
FT = 2.0102414060038662
F < FT: True


## Второй пункт. Доверительные интервалы

In [14]:
true_tetta = [2,2.5,0.03,0.1,-2,0.001]
for j in range(0,6):
    sigma_tetta_wave_j = (LinModel.for_sigma[j][j]*sigma_sq_predict)**(1/2)
    print(f'Минимальное значение:{tetta[j]-FT*sigma_tetta_wave_j}<={true_tetta[j]}<= Макс.знач{tetta[j]+FT*sigma_tetta_wave_j}')

Минимальное значение:1.4541098691987226<=2<= Макс.знач2.5457112190934232
Минимальное значение:2.0866236981321173<=2.5<= Макс.знач2.691765854165508
Минимальное значение:-0.9732988192311143<=0.03<= Макс.знач0.30245286160256457
Минимальное значение:-1.3995114208699557<=0.1<= Макс.знач0.6333269275893336
Минимальное значение:-2.1397987320908354<=-2<= Макс.знач-0.9961875515866955
Минимальное значение:-0.7314025920592666<=0.001<= Макс.знач1.52382906950981


## Третий пункт. Гипотеза о незначимости параметра

In [15]:
#значение F критического, с которым будем сравнивать
F_crit=scipy.stats.f.isf(0.05,1,n-6)
print(F_crit)

4.600109936669421


In [16]:
for j in range(0,6):
    djj=LinModel.for_sigma[j][j]*sigma_sq_predict
    F = (tetta[j]**2)/djj
    print(f" Номер: {j},Значение F={F}, F<fcrit  {F<F_crit}")

 Номер: 0,Значение F=54.25620729934888, F<fcrit  False
 Номер: 1,Значение F=251.96760974213052, F<fcrit  False
 Номер: 2,Значение F=1.117402771447905, F<fcrit  True
 Номер: 3,Значение F=0.5740602221794833, F<fcrit  True
 Номер: 4,Значение F=30.387008831014484, F<fcrit  False
 Номер: 5,Значение F=0.49892132230184716, F<fcrit  True


## Четвертый пункт. Проверка гипотезы о незначимости самой регрессии

In [17]:
# theta - массив найденных параметров
theta_intercept = LinModel.get_param()[1]
theta = LinModel.get_param()[0]
theta = np.append(theta_intercept, theta)
theta

array([ 1.99991054,  2.38919478, -0.33542298, -0.38309225, -1.56799314,
        0.39621324])

In [18]:
# Формулы:
# F = (RSSh - RSS) * (n - m) / q / RSS
# RSSh = sum( ( yi - y_aver )^2 )
# RSS = (y - X*theta)T * (y - X*theta)

m = theta.size
q = m - 1
X_wout_intercept = np.array(x)
X_arr = np.hstack((np.ones((X_wout_intercept.shape[0], 1)), X_wout_intercept))

rssh = 0
rss = np.dot((y - np.dot(X_arr, theta)).T, (y - np.dot(X_arr, theta)))

# y_aver - среднее истинного y
y_aver = np.average(y)
for i in range(n):
  rssh += pow((y[i] - y_aver), 2)

F_regr_level = ((rssh - rss) / q) / (rss / (n - 6))
FT_regr_level = scipy.stats.f.ppf(q=1-0.05, dfn=q, dfd=n-m)

print('Незначимость регресии: ')
print('F = ', F_regr_level)
print('FT = ', FT_regr_level)
print('F < FT', F_regr_level < FT_regr_level)

Незначимость регресии: 
F =  56.80933564360462
FT =  2.958248913122196
F < FT False


## Пятый и шестой пункты. Доверительное оценивание для мат. ожидания
#### для истинного значения математического ожидания функции отклика в точке фиксированной

In [19]:
# фиксируем x1 = -1
X1 = x1[0]
X2 = x2[0]

# оригинальная тетта
theta_original = np.array([2, 2.5, 0.03, 0.1, -2, 0.001])

# Считаем корень из F(alpha, 1, fR)
F_di = pow(scipy.stats.f.ppf(q=1-0.05, dfn=1, dfd=n-m), 0.5)

i = 0
while (X2 <= x2[4]):
    func = np.array([1, X1, X1**2, X2, X2**2, X1**3])
    # считаем сигму
    sigma_new = pow(sigma_sq_predict, 0.5) * pow(np.dot(np.dot(func.T, np.linalg.inv(np.dot(X_arr.T, X_arr)) ), func), 0.5) 
    
    # считаем этту
    nu = np.dot(func.T, theta)

    # считаем границы
    nu_min = nu - F_di * sigma_new
    nu_max = nu + F_di * sigma_new
    # что есть этта оригинал?
    nu_original = np.dot(func.T, theta_original)
    X2 = X2 + 0.2

    # чтобы удобней переносить в эксель было
    print(f'{nu_min},{nu_original},{nu_max}')
    i += 1

-3.0060817973785205,-2.5709999999999997,-1.605560892102961
-2.5059766071036402,-1.831,-1.1299479189100543
-2.253163041078463,-1.2510000000000001,-0.6579222241616471
-2.1823288433201133,-0.8310000000000001,-0.25479606384061526
-2.2540069885628817,-0.5710000000000001,0.039963536787332554
-2.453192417669243,-0.471,0.21135151858467016
-2.77677428717372,-0.5309999999999999,0.25625703808592193
-3.2271921716023897,-0.751,0.17711966981716376
-3.809701006042835,-1.1309999999999998,-0.02080565113402133
-4.5309912814132085,-1.671,-0.330828433849482
-5.398287745393483,-2.371,-0.7457239306492429


### Доверительное оценивание для мат. ожидания
#### для истинного значения математического ожидания самого отклика

In [20]:
# фиксируем х = -1
X1 = x1[0]
X2 = x2[0]

# Считаем корень из F(alpha, 1, fR)
F_di = pow(scipy.stats.f.ppf(q=1-0.05, dfn=1, dfd=n-m), 0.5)

while (X2 <= x2[4]):
    func = np.array([1, X1, X1**2, X2, X2**2, X1**3])

    # считаем сигму
    sigma_new = pow(sigma_sq_predict * (1 + np.dot(np.dot(func.T, np.linalg.inv(np.dot(X_arr.T, X_arr))), func)), 0.5)

    y_pr = np.dot(func.T, theta)
    y_min = y_pr - sigma_new * F_di
    y_max = y_pr + sigma_new * F_di
    # вот тут вопрос: что есть у оригинал
    y_original = np.dot(func.T, theta_original)
    X2 = X2 + 0.2
    
    print(f'{y_min},{y_original},{y_max}')
    i += 1

-3.644866276018182,-2.5709999999999997,-0.9667764134632992
-3.1506439069617267,-1.831,-0.48528061905196807
-2.8479775296406293,-1.2510000000000001,-0.06310773559948069
-2.712390516124153,-0.8310000000000001,0.2752656089634242
-2.725123026562496,-0.5710000000000001,0.5110795747869468
-2.8752366193099292,-0.471,0.6333957202253568
-3.158282960913932,-0.5309999999999999,0.637765711826134
-3.57442918658325,-0.751,0.5243566847980241
-4.126951461034114,-1.1309999999999998,0.2964448038572578
-4.821102028350051,-1.671,-0.04071768691263955
-5.663195553001376,-2.371,-0.480816123041349
